### ISSUE TITLE
Admin rights (for projects)

### ISSUE THREAD

**Issue by anielakob** [Stribe02/Project-VI#11]
Currently lacking admin rights to add and edit projects
<img width="362" alt="Screenshot 2023-10-31 at 23 34 16" src="https://github.com/Stribe02/Project-VI/assets/26513230/aa87dc32-e81d-414a-b0c1-cb92da692558">

**Comment by anielakob** [comment]
Last comment here before I get on my bike, 
have you tried adding me as a collaborator on the project itself? Without making an org?

This is all very weird and confusing lol

<img width="1142" alt="Screenshot 2023-11-01 at 10 04 06" src="https://github.com/Stribe02/Project-VI/assets/26513230/c3081a8a-17c9-4658-8355-6b9ccbf913e9">

**Comment by Stribe02** [comment]
The classic projects was tied to a specific repo.. now they are tied to a user or an org :/ Money talks i suppose. I have added two more boards and given admin rights to you.. I will add more placeholder projects that hopefully you can edit their names xD

**Comment by anielakob** [comment]
Will see if editing name is possible in browser 👍

**Comment by anielakob** [comment]
This goes to show why using the ITU GitHub is maybe actually kinda cool?

No paywallllsss

**Comment by anielakob** [comment]
Can confirm that both names _and_ access is editable by me, _also_ **deleting** projects is possible now???
